### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by tkdguraa** [unbiarirang/WeChatTicket#6]
**Describe the problem if you have**
无

**Describe the feature**
找出了一些Bug,会不时地更新
- [x] 当没有票的时候，点击查票会出错
- [x] 输入book可以买活动结束的票，而且抢啥里也会出现那个票
- [x] 退票有问题，虽然显示退票成功，但是实际没有退票，且即使没有拥有的票，输入
退票也会显示退票成功。
  ...

**Deadline**
2018-10-20

**Additional context**
无

**Comment by unbiarirang** [comment]
thanks

**Comment by tkdguraa** [comment]
Good
