### ISSUE TITLE
Bug Report Version 2

### ISSUE THREAD

**Issue by tkdguraa** [unbiarirang/WeChatTicket#7]
**Describe the problem if you have**
无

**Describe the feature**
找出了一些Bug,会不时地更新
- [x] 创建活动时，活动名称和活动代称可重复
- [x] GetDetail中的get操作之後，id值未傳遞  
...

**Deadline**
2018-10-20

**Additional context**
今天是DDL要抓紧时间！

**Comment by unbiarirang** [comment]
创建活动时，活动名称和活动代称可重复 -> 服务器不接受重复名称，但front存在一些问题。
